error writing "file19ab8329570": broken pipe
error writing "file19ab8329570": broken pipe
    while executing
"puts -nonewline $fd "[encoding convertto utf-8 $path]\0""
    (procedure "write_update_index" line 35)
    invoked from within
"write_update_index file19ab8329570 {API/API-selbst/Daten.dat API/API-selbst/__pycache__/help.cpython-38.pyc API/API-selbst/__pycache__/main.cpython-38..."